name: Daily Auto Push

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Make Commit
        run: |
          git config user.name "github-actions"
          git config user.email "javlin77@users.noreply.github.com"
          git commit --allow-empty -m "Daily auto update"
          git push
